### ISSUE TITLE
Example code to learn usage?

### ISSUE THREAD

**Issue by wklenk** [evert/hal-types#31]
Hi,

thanks for these HAL type definitions.
Is there some example code that displays how to use them when fetching record-type data from a backend system (e.g. implemented using Spring Data Rest) ?

I wonder if this _HalResource_ needs to be customized somehow, to add some information about the record-type data, e.g. a _HalResource<Customer>_ or something similar. In the TypeScript code in React, I have the need to iterate over all records in this _HalResource_.

**Comment by evert** [comment]
Hi @wklenk , you might like my other project Ketting:

https://github.com/badgateway/ketting

And React-Ketting:

https://github.com/badgateway/react-ketting

**Comment by arucard21** [comment]
I wrote some usage documentation for my own project (which uses this library). I think this (modified) excerpt from it may be useful as usage documentation for this library. You can include this in your readme if you want.

> This example shows how to create a TypeScript type for your HAL-based resource, by extending the `HALResource` type.
```TypeScript
import { HalResource } from 'hal-types';

export type ExampleResource<T extends HalResource = HalResource> = {
    name: string;
    someAttribute: {
        attributeName: string;
    };
} & T;
```

**Comment by arucard21** [comment]
I went ahead and created PR #47 for this.
